name: Code Coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    env:
      OS: ubuntu-latest
      NODE_VERSION: ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate coverage report
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        env_vars: OS,NODE_VERSION
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
